using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SimpleAuthenticationAPI.Models
{
    /// <summary>
    /// A base class
    /// </summary>
    public abstract class BaseEntity
    {
        /// <summary>
        /// A primary key id generated by the database
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity),Key]
        public Guid Id { get; set; }
    }
}
